/* GENERATED BY Meta_Grammar.g4 */

grammar Grammar;

@members {
}


main :
{
}
;



/* LEXER */

WORD : (CHAR)+ 
;

WS : ([ \t\r\n]|COMMENT) -> skip 
;

fragment CHAR : [a-zA-ZáéíóúÁÉÍÓÚâêîôûÂÊÎÔÛãõÃÕàèìòùÀÈÌÒÙçÇ_] 
;

fragment COMMENT : '/*'.*?'*/' | '//'~('\r'|'\n')* 
;

